const fs = require('fs')
const path = require('path')
fs.writeFileSync('../rd-example/lib/rd-runtime.mjs', fs.readFileSync('dist/rd-runtime.mjs'))
fs.writeFileSync('../rd-example/lib/rd-runtime.mjs.map', fs.readFileSync('dist/rd-runtime.mjs.map'))
fs.writeFileSync('../rd-example/lib/rd-runtime.umd.js', fs.readFileSync('dist/rd-runtime.umd.js'))
fs.writeFileSync('../rd-example/lib/rd-runtime.umd.js.map', fs.readFileSync('dist/rd-runtime.umd.js.map'))
fs.writeFileSync('../rd-example/lib/index.css', fs.readFileSync('dist/index.css'))

fs.writeFileSync('../../rich-data-play/lib/rd-runtime.mjs', fs.readFileSync('dist/rd-runtime.mjs'))
fs.writeFileSync('../../rich-data-play/lib/rd-runtime.mjs.map', fs.readFileSync('dist/rd-runtime.mjs.map'))
fs.writeFileSync('../../rich-data-play/lib/rd-runtime.umd.js', fs.readFileSync('dist/rd-runtime.umd.js'))
fs.writeFileSync('../../rich-data-play/lib/rd-runtime.umd.js.map', fs.readFileSync('dist/rd-runtime.umd.js.map'))
fs.writeFileSync('../../rich-data-edit/lib/index.css', fs.readFileSync('dist/index.css'))

fs.writeFileSync('../../rich-data-edit/lib/rd-runtime.mjs', fs.readFileSync('dist/rd-runtime.mjs'))
fs.writeFileSync('../../rich-data-edit/lib/rd-runtime.mjs.map', fs.readFileSync('dist/rd-runtime.mjs.map'))
fs.writeFileSync('../../rich-data-edit/lib/rd-runtime.umd.js', fs.readFileSync('dist/rd-runtime.umd.js'))
fs.writeFileSync('../../rich-data-edit/lib/rd-runtime.umd.js.map', fs.readFileSync('dist/rd-runtime.umd.js.map'))
fs.writeFileSync('../../rich-data-edit/lib/index.css', fs.readFileSync('dist/index.css'))

console.log('拷贝完成')